const objects=[
    {
        id:1,
        name:"ayush",
        lastname:"chaurasia"
    },
    {
        id:2,
        name:"anish",
        lastname:"chaurasia"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
    ,{
        id:3,
        name:"siddharth",
        lastname:"singh"
    }
];
export default objects